name: Bench
on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: write
    deployments: write

jobs:
    benchmark:
        name: Run Rust benchmark 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: rustup toolchain update nightly && rustup default nightly
            - name: Run benchmark
              run: cd benches && rm -r output.txt && touch output.txt && cargo +nightly bench | tee output.txt
              