on:
    pull_request:
    push:
        branches:
            - main

name: Check and Lint

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: Cache cargo
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

    - name: Build
      run: cargo build --verbose
  
    - name: fmt
      run: cargo fmt --all -- --check
